import React, { useState } from 'react';
import { useStore } from '../store/useStore';

interface Article {
  id: string;
  title: string;
  category: string;
  summary: string;
  howItWorks: string;
  warnings: string[];
  detection: string;
  prevention: string[];
}

export default function ScamCenter() {
  const { setActiveTab } = useStore();
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  const articles: Article[] = [
    {
      id: 'internship',
      title: 'Fake Internship Scams',
      category: 'Employment',
      summary: 'Scammers offer high-paying virtual work or training opportunities to extract registration fees or personal identity documents.',
      howItWorks: 'You receive an unsolicited message on WhatsApp/Telegram offering a part-time job or virtual internship. They ask you to complete simple tasks (like liking videos) and then demand deposit fees to unlock higher payout levels.',
      warnings: [
        'Unsolicited internship offers via direct messaging apps.',
        'Demands for money to clear registration, laptops, or background verification checks.',
        'High payouts promised for very basic tasks (e.g. 5,000 INR per day for liking videos).'
      ],
      detection: 'PARAKH scans company URL registries, registrar ages, and verifies if company domains are lookup targets for spoofing templates. It also checks metadata of PDF offer documents to reveal author software.',
      prevention: [
        'Never pay money to get an internship or job.',
        'Directly verify with the HR department of the company via their official website support contact.'
      ]
    },
    {
      id: 'upi',
      title: 'UPI Payment Frauds',
      category: 'Financial',
      summary: 'Attackers send collection requests or mock confirmation screenshots to trick victims into entering UPI PINs to "receive" money.',
      howItWorks: 'Scammers send a payment link or QR code claiming they are sending you money. In reality, they send a "Collect Request". Clicking it and entering your UPI PIN authorizes the transfer of money *out* of your account.',
      warnings: [
        'Entering your UPI PIN to "receive" or "refund" money. (PIN is ONLY needed to SEND money).',
        'Incoming SMS alerts showing collection warnings from banks.'
      ],
      detection: 'PARAKH processes payment confirmation screenshots, scanning pixels for double-quantization compression anomalies and metadata modifications that indicate the text values were edited.',
      prevention: [
        'Remember: UPI PIN is never required to receive money.',
        'Directly check your bank account balance instead of relying on SMS notifications or screenshots.'
      ]
    },
    {
      id: 'offer',
      title: 'Fake Offer Letters',
      category: 'Employment',
      summary: 'Forged employment letters containing company letterheads used to demand training deposits or visa processing fees.',
      howItWorks: 'Victims apply on job portals and receive fake selection offer letters on lookalike company letterheads. Scammers ask for visa processing or laptop configuration deposits.',
      warnings: [
        'Sender emails coming from free providers (Gmail, Outlook) instead of corporate domains.',
        'No face-to-face or video interviews conducted before selecting candidates.'
      ],
      detection: 'PARAKH Document Integrity scans PDF internal markers to identify author software (e.g. Canva or online PDF editors) and checks digital hashes against official templates.',
      prevention: [
        'Check if the sender email domain matches the official website domain.',
        'Corporate HR departments do not request processing deposits or use free Gmail addresses.'
      ]
    },
    {
      id: 'deepvoice',
      title: 'Deepfake Voice Calls',
      category: 'AI Synthetic',
      summary: 'Cloned voices of family members or CEOs generated by AI to demand immediate emergency transfers.',
      howItWorks: 'Attackers harvest vocal samples from social media, clone the voice using generative software, and call family members pretending to be in an emergency (accidents, arrests) to ask for money.',
      warnings: [
        'Callers refusing to answer security questions known only to the family.',
        'Urgent demands for cash or immediate UPI transfers.'
      ],
      detection: 'PARAKH Voice Authentication runs spectral checks, analyzing vocal tract harmonics, acoustic continuity, and noise maps to identify synthetic speech markers.',
      prevention: [
        'Hang up and call the family member back on their known, saved number.',
        'Establish a secret family passcode to confirm identity during emergencies.'
      ]
    },
    {
      id: 'aadhaar',
      title: 'Fake Aadhaar/PAN Card Spoofing',
      category: 'Identity',
      summary: 'Altered identity cards containing fake photos or text values used to open fraudulent accounts.',
      howItWorks: 'Scammers edit digital copies of Aadhaar/PAN cards using graphic software to bypass online KYC verifications or rent properties.',
      warnings: [
        'Mismatched fonts, misaligned QR codes, or uneven borders on identity documents.',
        'Low-resolution copies where text elements are blurred.'
      ],
      detection: 'PARAKH parses image compression tables, tracking pixel variances around font boundaries, and cross-checks the embedded secure QR code data.',
      prevention: [
        'Always verify paper Aadhaar cards using UIDAI\'s secure QR scanner application.',
        'Do not share high-resolution unmasked scans of identity cards online.'
      ]
    },
    {
      id: 'otp',
      title: 'WhatsApp OTP Scams',
      category: 'Identity',
      summary: 'Tricksters hijack user accounts by convincing them to share WhatsApp verification codes.',
      howItWorks: 'A scammer messages you pretending to be a support agent or a friend who "accidentally" sent a code to your phone, urging you to share it.',
      warnings: [
        'Unsolicited verification codes arriving via SMS.',
        'Calls from strangers requesting numeric codes to "prevent account suspension".'
      ],
      detection: 'PARAKH logs suspicious links and registrar databases, preventing navigation to fake OTP verification pages.',
      prevention: [
        'Never share verification codes (OTP) with anyone, for any reason.',
        'Enable two-step verification inside your WhatsApp security settings.'
      ]
    },
    {
      id: 'qrscam',
      title: 'QR Code Payment Scams',
      category: 'Financial',
      summary: 'Fake QR codes pasted on store counters or sent via chat to divert payments to hacker wallets.',
      howItWorks: 'Scammers paste lookalike payment stickers over merchant counter QRs, or send QRs via WhatsApp claiming you won a lottery sweepstakes.',
      warnings: [
        'Scanning QR codes sent on chat forums to "receive rewards".',
        'Physical payment stickers showing signs of peeling or double layers.'
      ],
      detection: 'PARAKH QR Scanner decodes destination links in a secure sandbox, highlighting phishing risks and redirect chains before you click.',
      prevention: [
        'Confirm the merchant name on your UPI screen matches the store name before executing transactions.',
        'Avoid scanning random QR codes found in public places.'
      ]
    },
    {
      id: 'investment',
      title: 'Investment & Trading Frauds',
      category: 'Financial',
      summary: 'Fake trading apps and crypto platforms showing high mock returns to lure victims into depositing large sums.',
      howItWorks: 'Victims are added to VIP WhatsApp groups discussing high returns. They are guided to download a trading app which shows fake growth charts, encouraging massive deposits.',
      warnings: [
        'Guaranteed high daily returns with zero risk.',
        'Demands to deposit funds into private personal accounts instead of trading broker accounts.'
      ],
      detection: 'PARAKH Website Verification audits the trading app URL registries, flagging newly created domains and offshore hosting profiles.',
      prevention: [
        'Only use stock brokers registered with SEBI or national regulators.',
        'If it sounds too good to be true, it is a scam.'
      ]
    },
    {
      id: 'courier',
      title: 'Fake Courier Messages',
      category: 'Communication',
      summary: 'Unsolicited messages claiming a parcel has been held due to unpaid customs or address verification.',
      howItWorks: 'You receive an SMS claiming your India Post or DHL package is delayed. You are asked to click a link and pay a small fee (e.g. 20 INR) to re-route it.',
      warnings: [
        'Messages about undelivered parcels you did not order.',
        'Urgent links urging payments to unlock address details.'
      ],
      detection: 'PARAKH Link Inspector analyzes message links, flagging tracking pixels, expired security certificates, and malware payloads.',
      prevention: [
        'Directly track shipments on the official carrier site using your tracking number.',
        'Never click links in SMS notifications from unknown sending IDs.'
      ]
    },
    {
      id: 'aiimage',
      title: 'AI Image & Deepfake Scams',
      category: 'AI Synthetic',
      summary: 'Fake images created by AI generators used to spread misinformation or fabricate evidence.',
      howItWorks: 'Scammers use text-to-image AI tools to create photorealistic images of political events, disasters, or celebrity endorsements to manipulate public opinion.',
      warnings: [
        'Unnatural skin textures, extra fingers, or distorted background text.',
        'Sensational news stories supported by a single photo from an unknown source.'
      ],
      detection: 'PARAKH scans pixel boundaries, noise distributions, and EXIF camera indicators, exposing synthetic signatures from Midjourney, Stable Diffusion, and Photoshop exports.',
      prevention: [
        'Reverse image search suspicious photos to find their origin.',
        'Rely on verified news outlets for critical breaking reports.'
      ]
    }
  ];

  const filteredArticles = articles.filter(art => 
    art.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    art.summary.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-6 md:p-8 space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black tracking-tight text-brand-850 flex items-center space-x-3">
            <span>🎓</span> <span>Scam Knowledge Center</span>
          </h2>
          <p className="text-brand-500 text-sm mt-1">
            Learn how online scams operate, recognize key warning signs, and understand how PARAKH forensic modules detect them.
          </p>
        </div>
        {!selectedArticle && (
          <button
            onClick={() => setActiveTab('dashboard')}
            className="self-start md:self-center px-4 py-2 bg-white border border-brand-200 hover:border-brand-350 text-brand-700 hover:text-brand-850 rounded-xl text-xs font-bold transition flex items-center gap-1.5 focus:outline-none shadow-sm"
          >
            <span>←</span> Back to Dashboard
          </button>
        )}
      </div>

      {!selectedArticle ? (
        <div className="space-y-6">
          <input
            type="text"
            className="w-full bg-white border border-brand-200 focus:border-accent-blue focus:ring-1 focus:ring-accent-blue rounded-2xl px-5 py-4 text-sm focus:outline-none placeholder-brand-400 text-brand-850 shadow-sm"
            placeholder="Search scam types (e.g. UPI, Internship, Deepfake)..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {filteredArticles.map(art => (
              <div 
                key={art.id} 
                onClick={() => setSelectedArticle(art)}
                className="bg-white border border-brand-200 hover:border-accent-blue rounded-3xl p-6 shadow-sm hover:shadow-md transition duration-200 cursor-pointer flex flex-col justify-between space-y-4"
              >
                <div className="space-y-2">
                  <span className="bg-brand-100 text-brand-700 text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-wider">
                    {art.category}
                  </span>
                  <h3 className="text-lg font-black text-brand-850">{art.title}</h3>
                  <p className="text-xs text-brand-550 leading-relaxed line-clamp-3">{art.summary}</p>
                </div>
                <div className="text-accent-blue text-xs font-bold hover:underline flex items-center gap-1.5">
                  Read Guide <span>→</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="bg-white border border-brand-200 rounded-3xl p-6 md:p-8 shadow-xl space-y-6 animate-fade-in">
          <button
            onClick={() => setSelectedArticle(null)}
            className="text-brand-500 hover:text-brand-800 text-xs font-bold flex items-center gap-1.5 focus:outline-none mb-4"
          >
            <span>←</span> Back to Scam Directory
          </button>

          <div className="space-y-4 border-b border-brand-200 pb-5">
            <span className="bg-brand-100 text-brand-700 text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-wider">
              {selectedArticle.category}
            </span>
            <h1 className="text-3xl font-black text-brand-850 leading-tight">{selectedArticle.title}</h1>
            <p className="text-brand-600 text-sm italic">{selectedArticle.summary}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
            <div className="space-y-5">
              <div className="space-y-2">
                <h3 className="font-black text-sm uppercase tracking-wider text-brand-500">How the scam works</h3>
                <p className="text-xs text-brand-700 leading-relaxed bg-brand-50 p-4 rounded-2xl border border-brand-100">{selectedArticle.howItWorks}</p>
              </div>

              <div className="space-y-2">
                <h3 className="font-black text-sm uppercase tracking-wider text-brand-500">Key Warning Signs</h3>
                <div className="space-y-2.5">
                  {selectedArticle.warnings.map((warn, i) => (
                    <div key={i} className="flex items-start space-x-2 text-xs">
                      <span className="text-accent-red mt-0.5">⚠️</span>
                      <span className="text-brand-750 font-medium">{warn}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="space-y-5">
              <div className="space-y-2">
                <h3 className="font-black text-sm uppercase tracking-wider text-brand-500">How PARAKH Detects It</h3>
                <p className="text-xs text-brand-700 leading-relaxed bg-accent-blue/5 p-4 rounded-2xl border border-accent-blue/10">{selectedArticle.detection}</p>
              </div>

              <div className="space-y-2">
                <h3 className="font-black text-sm uppercase tracking-wider text-brand-500">How to Stay Safe</h3>
                <div className="space-y-2.5">
                  {selectedArticle.prevention.map((prev, i) => (
                    <div key={i} className="flex items-start space-x-2 text-xs">
                      <span className="text-accent-green mt-0.5">✓</span>
                      <span className="text-brand-750 font-semibold">{prev}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
